import PaintStore from '@/assets/paintStore.png';
import Estancia from '@/assets/estancia.png';
import CriselUI from '@/assets/criselui.webp';
import CriselAdmin from '@/assets/criseladmin.webp';
import BrothersAutoDetail from '@/assets/brothersAutoDetail.webp';
import FormulaCalculator from '@/assets/formula-calculator.webp';
import TeslaClonHome from '@/assets/tesla.webp';
import ProjectsDesign from '@/assets/projects-desing.webp';
import TodoApp from '@/assets/todo-app.webp';

import type { Project } from '@/components/organisms/Projects/Projects.types';
import { PATHS } from '@/routes/paths';

export const dataProjects: Project[] = [
  {
    id: 1,
    disabled: false,
    refWork: true,
    notCode: true,
    title: 'Pinturas Shaddai',
    img: PaintStore,
    tools: [
      'React',
      'Antd',
      'Tailwind',
      'Styled Components',
      'Axios',
      'React Router Dom',
      'Vite',
      'Playwright',
    ],
    visitPrev: PATHS.paintStore,
    descriptionKey: 'textOne',
  },
  {
    id: 2,
    disabled: false,
    refWork: true,
    notCode: true,
    title: 'Estancia Web Page',
    img: Estancia,
    tools: [
      'React',
      'Tailwind',
      'Styled Components',
      'Firebase',
      'Hosting',
      'React Router Dom',
      'Vite',
    ],
    visitPrev: 'https://estancia-website-4eb0d.web.app/',
    descriptionKey: 'textTwo',
  },
  {
    id: 3,
    disabled: false,
    refWork: true,
    notCode: true,
    title: 'Crisel Fronted UI',
    img: CriselUI,
    tools: [
      'React',
      'Antd',
      'Styled Components',
      'Firebase',
      'Hosting',
      'React Router Dom',
      'Vite',
    ],
    visitGit: 'https://github.com/ActoSoft/crisel-frontend-ui',
    visitPrev: PATHS.criselUI,
    descriptionKey: 'textThree',
  },
  {
    id: 4,
    disabled: false,
    refWork: true,
    notCode: true,
    title: 'Crisel Admin App',
    img: CriselAdmin,
    tools: ['Next', 'React', 'Antd', 'Styled Components', 'Firebase', 'Hosting'],
    visitGit: 'https://github.com/ActoSoft/crisel-frontend-erp',
    visitPrev: PATHS.criselAdmin,
    descriptionKey: 'textFour',
  },
  {
    id: 5,
    refWork: true,
    notCode: false,
    disabled: false,
    title: 'Brothers Auto Details',
    img: BrothersAutoDetail,
    tools: ['Next', 'React', 'Tailwind', 'Firebase', 'Axios', 'Hosting', 'Antd'],
    visitGit: 'https://github.com/ActoSoft/brothers-auto-detail-ui',
    visitPrev: 'https://brothersautodetails.web.app/',
    descriptionKey: 'textFive',
  },
  {
    id: 6,
    refWork: false,
    notCode: false,
    disabled: false,
    title: 'Formula Calculator',
    img: FormulaCalculator,
    tools: ['React', 'Css', 'React Router Dom', 'Vite', 'Vercel'],
    visitGit: 'https://github.com/SantiMelo7/Calculator-Formula',
    visitPrev: 'https://calculator-formula-math.vercel.app/',
    descriptionKey: 'textSix',
  },
  {
    id: 7,
    refWork: false,
    notCode: false,
    disabled: false,
    title: 'Tesla Clon | Home',
    img: TeslaClonHome,
    tools: ['React', 'Tailwind', 'Vite', 'Vercel'],
    visitGit: 'https://github.com/SantiMelo7/Tesla-Clon-Home',
    visitPrev: 'https://tesla-clon-home-bie1f0e1t-santicms-projects.vercel.app/',
    descriptionKey: 'textSeven',
  },
  {
    id: 8,
    disabled: false,
    refWork: false,
    notCode: false,
    title: 'Design Projects',
    img: ProjectsDesign,
    tools: ['Html', 'Css', 'Sass'],
    visitGit: 'https://github.com/SantiMelo7/Aprendiendo-HTML-Y-CSS',
    visitPrev: PATHS.desingProjects,
    descriptionKey: 'textEight',
  },
  {
    id: 9,
    disabled: false,
    refWork: true,
    notCode: false,
    title: 'To Do List',
    img: TodoApp,
    tools: ['Html', 'Javascript', 'Css'],
    visitGit: 'https://github.com/SantiMelo7/Aprendiendo-HTML-Y-CSS/tree/main/todooooos',
    visitPrev: 'https://todos-app-11111.netlify.app',
    descriptionKey: 'textNine',
  },
];
